### ISSUE TITLE
Failing to run on Windows

### ISSUE THREAD

**Issue by Lichtschalter-5000** [goto-bus-stop/wikibattle#165]
I'm working on Win10x64.
npm Version 6.14.5

`$ npm install` delivers following warnings:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\postcss-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
`$ npm start` the following:
```
> wikibattle@1.5.1 start [...]\wikibattle
> bin/wikibattle

Der Befehl "bin" ist entweder falsch geschrieben oder ("Command 'bin' was spelled wrong)
konnte nicht gefunden werden. (or couldn't be found.")
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wikibattle@1.5.1 start: `bin/wikibattle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wikibattle@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    [...]\AppData\Roaming\npm-cache\_logs\2020-06-17T08_19_31_038Z-debug.log

```
`$ node bin/wikibattle` at least works as such, but I will get this error message when looking at `localhost:3000`:
```
Not Found
404
Error: Not Found
    at [...]\wikibattle\src\app.js:99:15
    at Layer.handle [as handle_request] ([...]\wikibattle\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix ([...]\wikibattle\node_modules\express\lib\router\index.js:317:13)
    at [...]\wikibattle\node_modules\express\lib\router\index.js:284:7
    at Function.process_params ([...]\wikibattle\node_modules\express\lib\router\index.js:335:12)
    at next ([...]\wikibattle\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error ([...]\wikibattle\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (events.js:209:13)
    at SendStream.error ([...]\wikibattle\node_modules\send\index.js:270:17)
    at SendStream.onStatError ([...]\wikibattle\node_modules\send\index.js:421:12)
```

Would you be so kind and point me to a place to start looking for the issue?
The stacktraces aren't really helpful for me.

I have also tried to tell npm to use the terminal which comes with Git for Windows, which delivered the same result in the browser.
Of course I deleted npm's cache and the node_modules more than once, I even deleted the whole directory once and cloned from GitHub again. 

Or is this rather a feature (not running under windows, only on Linux or OSX) than a bug?

**Comment by goto-bus-stop** [comment]
we can change the `"start"` script to do `node bin/wikibattle`!

For the second issue, I think the html file isn't copied correctly. `npm run html` copies the index.html file from src/client/index.html in the public/ folder, which contains all the public static files. I think we may need to add it to the `"prod"` npm script at the end? `npm run html` is _probably_ not windows-compatible unless you use mingw.
(A cool PR would be to use https://www.npmjs.com/package/cpy-cli instead of `cp`!)
