### ISSUE TITLE
You can cheat.

### ISSUE THREAD

**Issue by Luca0208** [goto-bus-stop/WikiBattle#3]
You can easily cheat by modifying a link to go to /wiki/<target> and click it, and that makes it REALLY easy to cheat if you know how to do it.

**Comment by goto-bus-stop** [comment]
Haha, yeah! a server-side check for that was supposed to be added at some point but I haven't got around to actually doing it yet. The methods to check that a page really does link to another page are already there: https://github.com/goto-bus-stop/WikiBattle/blob/master/lib/wiki.js#L25-L35 However obviously not yet used :)

I can pick this up this weekend, but feel free to send a PR if you have the time/will too :)

**Comment by Luca0208** [comment]
I created a PR( #4 )
