### ISSUE TITLE
exclude more articles from being picked as a start or goal article

### ISSUE THREAD

**Issue by goto-bus-stop** [goto-bus-stop/wikibattle#73]
someone got this:

![image](https://user-images.githubusercontent.com/1006268/50057085-e82b7e80-0165-11e9-8d12-72492fb4c07d.png)

which is not a good time.

i should also look into if there's some sort of content rating mechanism for/on wikipedia again

e; https://github.com/goto-bus-stop/wikibattle/issues/159 also ran into a not very fun article!

**Comment by goto-bus-stop** [comment]
maybe a start would be to do a rudimentary filter based on words in the article title … that'll have false positives but that's not the worst thing for a silly game like this

**Comment by Lichtschalter-5000** [comment]
Uhm, I'd consider reopening this for also removing the '-' which is always included in the articles...
If it were "Hyphen", that could technically work, but I think "Goal: - " would be confusing for most users.

I think this can be solved by either adding to the `isFunPageName`-Method or just starting to search the list at the third entry in `loadPages()`. The first two seem to be constantly the Start Page and the Hyphen.

**Comment by goto-bus-stop** [comment]
The main page is already excluded by `isWikiPageLink` (maybe a bit strange that there's now two different exclusion paths but ok)

Good call about the hyphen, I hadn't landed on that yet and it's fine as a starting article, but as a goal it's definitely not great!

**Comment by Lichtschalter-5000** [comment]
Just going through the list...
 - _Murder_
 -  _Death(s)_ (in 2020, huh! 😳 )
 - anything containing _chronic_ could be blacklisted, those are predominantly diseases and stuff
 - **definitely** _Main page_. This would be so confusing.

I think there is the chance of blacklisting some kind of film or game - but that's probably acceptable.

Also, for fun you could always add _[Wikiracing](https://en.wikipedia.org/wiki/Wikiracing)_ to the list, hehehe. 😁

**Comment by Lichtschalter-5000** [comment]
> The main page is already excluded by `isWikiPageLink` 

Yes (in theory) and no (I just spotted it in the actual list that's stored: "Main page")
This is the issue:
```
function isWikiPageLink (el) {
  const href = el.attribs.href
  return href !== '/wiki/Main_Page' && /^\/wiki\//.test(href)
}
```
The comparison to `'/wiki/Main_Page`' should definitely be case-insensitive.

**Comment by goto-bus-stop** [comment]
Ohhhhhh I see now, it's on the list twice! That makes sense, thanks lol
